### PR TITLE
Add exemple usage of Android Views

### PR DESCRIPTION
**Pull request by zenith391**

### CODE REVIEW

**Comment by zenith391** [comment]
I added a `-Dexample` option to choose which example to run.
Doing this, I renamed the current one to `egl` and the new one is named `textview`

**Comment by ikskuh** [comment]
> I added a `-Dexample` option to choose which example to run. Doing this, I renamed the current one to `egl` and the new one is named `textview`

Sounds good!

**Comment by ikskuh** [comment]
How ready is this for merge?

**Comment by zenith391** [comment]
It's ready!

**Pull request merged**
