### PR TITLE
Run on arm 32-bit 

### PR DESCRIPTION
**Pull request by desttinghim**
Depends on https://github.com/ziglang/zig/pull/13245

Also switches from using jarsigner to using apksigner.

The primary change for ZigAndroidTemplate to support arm 32-bit is using `c_long` instead of `i64` for the times returned from `getDownTime` and `getEventTime`.

### CODE REVIEW

**Comment by ikskuh** [comment]
Hey, that looks good!

Can you check if we still need the JDK path in the build-config files? if not, we can remove that dependency.

**Comment by desttinghim** [comment]
It looks like we still need the JDK for `keytool`, unfortunately. If that could be replaced there would be no need to have the JDK.

**Comment by desttinghim** [comment]
I figured out why the app was using 32-bit - the library was being put into the wrong folder. The correct one is `lib/arm64-v8a`. The changes made to compiler_rt and the zig standard library are still necessary to get the 64-bit version working on my tablet. I'm not sure why there's a discrepancy between my phone and the tablet. I'm not sure if the changes I made have broken support for my phone, I can't get it to connect to my computer right now.

- My phone is a OnePlus 5, with a Qualcomm Snapdragon 835 SoC
- My tablet is a Samsung Galaxy Tab S6 Lite, using an Exynos 9610

Both of them use the `arm64-v8a` isa, though the 835 is a semi-custom version of the isa.

**Comment by ikskuh** [comment]
i fixed the arm64-v8a thing locally, also improved on a lot of other stuff too. will merge the PR if you give me the ok.

**Comment by desttinghim** [comment]
I'm fine with merging this, as long as it works for you.

**Pull request merged**
