### PR TITLE
Minor fixes for windows code paths

### PR DESCRIPTION
**Pull request by JonSnowbd**

### CODE REVIEW

**Comment by aicarambazigalo** [comment]
Looks like you were able to build this on Windows at some point.
Can you still build it on Windows today with zig9? is it under windows 10 or 7 ?

**Comment by JonSnowbd** [comment]
Never really built this directly, the fixes included were syntactical errors hit by zig's pre-llvm stuff, as a consequence of building something that relied on this for android support, but never hit any of the code paths in this library.

**Comment by aicarambazigalo** [comment]
I see this code is already in master as https://github.com/MasterQ32/ZigAndroidTemplate/commit/237f61a6a7bdae72686d5b306284d0d0f4a61756#diff-03d5931e5abd662292b2542125b6fa08a29424e384bf3789ea79c676ff492418

**Comment by ikskuh** [comment]
> I see this code is already in master as …

Closing now, as windows build seems to work

**Pull request closed without merging**
